export function mountAdminAlerts({api,container,notice}){
 const section=document.createElement('section');section.className='wide';section.id='automaticAlerts';
 section.innerHTML='<h2>Avisos automáticos</h2><p>El servidor comprueba cada cinco minutos el proveedor, las reproducciones y las copias, aunque este panel esté cerrado. Un fallo persistente abre una incidencia; la recuperación comprobada cierra esa incidencia.</p><p id="alertSummary" role="status" aria-live="polite">Cargando vigilancia…</p><div id="alertIncidents"></div><details><summary>Configurar avisos</summary><form id="alertForm"><label><input name="enabled" type="checkbox" style="width:auto"> Vigilancia activada</label><label>Recibir avisos<select name="channel"><option value="panel">Solo en el panel</option><option value="email">Panel y correo electrónico</option></select></label><div id="alertEmailFields" hidden><label>Correo que recibe los avisos<input name="to" type="email" maxlength="254" autocomplete="email"></label><label>Correo remitente verificado en Resend<input name="from" type="email" maxlength="254" autocomplete="off"></label><label>Clave de envío de Resend<input name="apiKey" type="password" maxlength="253" autocomplete="new-password" placeholder="Vacío: conservar la clave guardada"></label><p>La clave se guarda cifrada y no se vuelve a mostrar. El remitente debe estar autorizado en tu cuenta de Resend.</p><a href="https://resend.com/api-keys" target="_blank" rel="noopener noreferrer">Abrir claves de Resend</a></div><div class="toolbar"><button type="submit">Guardar avisos</button><button type="button" id="alertTest" class="secondary" disabled>Enviar correo de prueba</button></div></form></details><div class="toolbar" style="margin-top:18px"><button type="button" id="alertRefresh" class="secondary">Actualizar estado</button><button type="button" id="alertCheck" class="secondary">Comprobar ahora</button></div><p id="alertDelivery" role="status"></p><details><summary>Historial de incidencias y avisos</summary><div id="alertHistory"></div></details><p>Proveedor: dos comprobaciones fallidas consecutivas. Reproducción: cinco fallos de inicio o errores; con al menos cinco inicios, también demora superior a 10 segundos o más del 2 % del tiempo cargando. Se utiliza una ventana reciente de hasta 15 minutos. Copias automáticas: fallos o más de 36 horas sin una copia nueva. La falta de muestras de reproducción no confirma una recuperación.</p>';
 container.append(section);const $=id=>section.querySelector('#'+id),form=$('alertForm');let epoch=0,busy=false,dirty=false;
 const date=value=>value?new Date(value).toLocaleString():'Todavía sin comprobación';
 const delivery={panel:'Registrado en el panel',pending:'Correo pendiente de envío',accepted:'Correo aceptado por el servicio de envío',failed:'No se pudo enviar el correo',cancelled:'Envío cancelado al cambiar la configuración',expired:'Envío vencido',queue_full:'Cola de correo completa'};
 function emailFields(){const on=form.elements.channel.value==='email';$('alertEmailFields').hidden=!on;for(const name of ['to','from'])form.elements[name].required=on}
 function render(data,fill=false){
  const config=data.settings,open=data.incidents.filter(i=>i.status==='open');
  $('alertSummary').textContent=!config.enabled?'Vigilancia pausada.':data.monitorStale?'La vigilancia aún no tiene una comprobación reciente. Última comprobación: '+date(data.lastCheckedAt):open.length?open.length+' incidencias abiertas · Comprobado: '+date(data.lastCheckedAt):'Sin incidencias confirmadas · Comprobado: '+date(data.lastCheckedAt);
  $('alertIncidents').replaceChildren();for(const incident of open){const article=document.createElement('article');article.style.cssText='border:1px solid #d89337;padding:14px;border-radius:8px;margin:12px 0;overflow-wrap:anywhere';const title=document.createElement('strong'),detail=document.createElement('p');title.textContent=incident.title;detail.textContent=(incident.detail?incident.detail+' · ':'')+'Desde '+date(incident.openedAt)+(incident.waitingForSamples?' · Sin muestras nuevas suficientes para confirmar recuperación.':'');article.append(title,detail);$('alertIncidents').append(article)}
  $('alertHistory').replaceChildren();for(const event of data.history){const p=document.createElement('p');p.textContent=date(event.createdAt)+' · '+event.changes.map(c=>({opened:'Incidencia: ',resolved:'Recuperado: ',removed:'Conexión retirada: ',test:'Prueba: '}[c.kind])+c.title).join(' / ')+' · '+(delivery[event.delivery]||'Registrado');p.style.overflowWrap='anywhere';$('alertHistory').append(p)}
  if(!data.history.length)$('alertHistory').textContent='Todavía no hay incidencias registradas.';
  const outcome=data.delivery;
  $('alertDelivery').textContent=config.channel==='panel'?'Los avisos están registrados en el panel. El correo está sin conectar.':outcome.status==='accepted'?'Último correo aceptado por el servicio de envío: '+date(outcome.at)+'. Comprueba también tu bandeja de entrada.':outcome.status==='email_backlog_full'?'La cola de correo está llena. Las incidencias siguen visibles en el panel.':outcome.status==='email_rejected'?'El servicio rechazó el envío. Revisa la clave y el remitente.':outcome.status==='email_configuration_failed'?'No se pudo leer la clave de envío. Vuelve a guardarla.':['email_unavailable','email_rate_limited'].includes(outcome.status)?'El envío no respondió o alcanzó su límite. Se reintentará mientras el aviso esté pendiente.':'Correo configurado. Envía una prueba para comprobar que lo recibes.';
  if(fill||!dirty){for(const key of ['to','from','channel'])form.elements[key].value=config[key]||'';form.elements.enabled.checked=config.enabled;form.elements.apiKey.value='';emailFields()}
  $('alertTest').disabled=!config.enabled||config.channel!=='email'||!config.keyConfigured||dirty;
 }
 async function refresh(){if(busy)return;const generation=epoch;busy=true;try{const data=await api('alerts-status');if(generation===epoch)render(data)}catch(error){if(generation!==epoch)return;if(['operation_not_allowed','monitor_unavailable'].includes(error.code)){$('alertSummary').textContent='Vigilancia pendiente de actualizar el servidor.';return}throw error}finally{busy=false}}
 form.oninput=()=>{dirty=true;$('alertTest').disabled=true;emailFields()};form.onchange=form.oninput;
 async function action(button,run,save=false){button.disabled=true;const generation=epoch;try{const data=await run();if(generation!==epoch)return;if(save)dirty=false;render(data,save)}catch(error){if(generation===epoch)notice(error.message)}finally{if(generation===epoch)button.disabled=button.id==='alertTest'?dirty||form.elements.channel.value!=='email':false}}
 form.onsubmit=e=>{e.preventDefault();action(form.querySelector('button[type="submit"]'),async()=>{const data=await api('alerts-settings',{enabled:form.elements.enabled.checked,channel:form.elements.channel.value,to:form.elements.to.value,from:form.elements.from.value,apiKey:form.elements.apiKey.value});notice('Configuración de avisos guardada.');return data},true)};
 $('alertRefresh').onclick=()=>refresh().catch(error=>notice(error.message));
 $('alertCheck').onclick=e=>action(e.target,()=>api('alerts-check'));
 $('alertTest').onclick=e=>action(e.target,()=>api('alerts-test'));
 return {refresh,clear(){epoch++;dirty=false;busy=false;form.reset();form.elements.apiKey.value='';$('alertIncidents').replaceChildren();$('alertHistory').replaceChildren();$('alertSummary').textContent='';$('alertDelivery').textContent='';$('alertTest').disabled=true;emailFields()}};
}
