import {mountAdminSeries} from './admin-series.js?v=43.10';
import {mountAdminSecurity} from './admin-security.js?v=43.5';
import {mountAdminOperations} from './admin-operations.js?v=43.4';
import {mountAdminCapacity} from './admin-capacity.js?v=43.8';

import {createProviderView} from "./admin-provider-view.js?v=43.8";
const API=(globalThis.SMNConfig?.api||'https://api.snaptvnow.com')+'/admin';let adminGeneration=0;let token=sessionStorage.getItem('smn_admin_token'),users=[],creating=true;const $=id=>document.getElementById(id);const errors={recovery_failed:'El ensayo no pudo comprobar la recuperación. Los datos actuales se conservan.',recovery_in_progress:'Ya hay un ensayo en curso. Actualiza el estado en unos momentos.',recovery_unavailable:'El ensayo estará disponible al actualizar el servidor.',backup_in_progress:'Ya hay una copia en curso. Actualiza el estado en unos momentos.',backup_changed:'La copia cambió durante la verificación. Selecciónala y verifica de nuevo.',backup_failed:'No se pudo crear la copia. La última copia guardada se conserva.',mfa_not_enabled:'Primero activa el segundo factor.',mfa_authenticator_required:'Para renovar los códigos utiliza los seis dígitos de Google Authenticator.',mfa_required:'Escribe el código del autenticador o un código de recuperación.',mfa_invalid:'Código incorrecto o ya utilizado. Usa el siguiente código del autenticador o uno de recuperación.',mfa_setup_expired:'La configuración venció. Iníciala de nuevo.',password_unchanged:'Elige una contraseña nueva diferente de la actual.',mfa_already_enabled:'El segundo factor ya está activado.',invalid_backup:'La copia no pertenece a este servidor, está dañada o tiene un formato incompatible.',restore_confirmation_required:'Escribe RESTAURAR para confirmar esta copia.',backup_too_large:'La copia excede el tamaño permitido.',invalid_server_url:'Usa una URL pública HTTP o HTTPS sin usuario, contraseña ni parámetros. Para una cuenta individual introduce solo servidor y puerto.',content_disabled:'Contenido deshabilitado para esta cuenta.',provider_unavailable:'No se pudo validar este servidor. La conexión anterior se conserva.',admin_required:'La sesión del administrador terminó.',setup_denied:'Configura una clave de activación válida en Cloudflare.',already_configured:'El administrador ya está creado.',invalid_credentials:'Usuario o contraseña incorrectos.',try_later:'Demasiados intentos. Espera 15 minutos.',username_exists:'Ese usuario ya existe.',password_length:'La contraseña debe tener entre 12 y 256 caracteres.',invalid_username:'Usa de 3 a 80 letras, números, punto, guion, @ o guion bajo.',invalid_expiry:'El vencimiento debe estar en el futuro.',xtream_disabled:'El acceso Xtream está deshabilitado.',invalid_setting:'La configuración no es válida.',provider_invalid:'CCF no confirmó una cuenta activa.',admin_unavailable:'No se pudo completar la operación del panel. Intenta nuevamente.',panel_invalid:'El panel CCF rechazó el inicio de sesión.',panel_unavailable:'No se pudo consultar el panel CCF. Intenta nuevamente.',panel_no_active_lines:'El panel no devolvió cuentas activas.',panel_format_changed:'Cambió el formato del panel CCF; es necesario actualizar el conector.',edit_conflict:'Otro cambio modificó la cuenta. Actualiza e inténtalo de nuevo.'};
function notice(s){$('notice').textContent=s}async function api(action,data={}){const generation=adminGeneration;try{const result=await SMNConnection.requestJSON(API,{method:'POST',headers:{'content-type':'application/json'},credentials:globalThis.SMNConfig?.cookieMode?'include':'omit',body:JSON.stringify({action,access_token:token==='cookie'?undefined:token,browser_cookie:globalThis.SMNConfig?.cookieMode,...data}),signal:AbortSignal.timeout(action==='xtream-series-check'?120000:60000)});if(generation!==adminGeneration)throw Error('session_changed');return result}catch(error){if(generation===adminGeneration&&error.status===401&&error.message==='admin_required'){token=null;sessionStorage.removeItem('smn_admin_token');showLogin()}error.code=error.code||error.message;error.message=SMNConnection.message(error,errors[error.message]||'No se pudo completar la operación'+(error.status?' (HTTP '+error.status+')':'')+'.');throw error}}
function showLogin(){adminGeneration++;providerView.clear();securityView.clear();operationsView.clear();capacityView.clear();seriesView.clear();$('dashboard').classList.add('hidden');$('login').classList.remove('hidden')}function showDashboard(){$('setup').classList.add('hidden');$('login').classList.add('hidden');$('dashboard').classList.remove('hidden')}
const providerView=createProviderView({document,api,notice,onInventory:snapshot=>capacityView.setInventory(snapshot)});
const securityView=mountAdminSecurity({api,notice,container:document.querySelector('#dashboard .grid'),onRestored:refresh,onFactorEnabled:()=>{adminGeneration++;token=null;sessionStorage.removeItem('smn_admin_token')},onSessionChanged:()=>{token=null;sessionStorage.removeItem('smn_admin_token');showLogin()}});
const operationsView=mountAdminOperations({api,notice,container:document.querySelector('#dashboard .grid')});
const capacityView=mountAdminCapacity({container:document.querySelector('#dashboard .grid')});
const seriesView=mountAdminSeries({api,container:$('xtreamSection')});
function fields(form){return Object.fromEntries(new FormData(form))}async function submit(form,fn){const btn=form.querySelector('button');btn.disabled=true;try{await fn()}catch(e){notice(e.message)}finally{btn.disabled=false}}
$('setupForm').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{await api('setup',fields(e.target));e.target.reset();$('setup').classList.add('hidden');$('login').classList.remove('hidden');notice('Administrador creado. Inicia sesión.')})};
$('loginForm').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{const d=await api('login',fields(e.target));token=d.access_token||(globalThis.SMNConfig?.cookieMode?'cookie':null);sessionStorage.setItem('smn_admin_token',token);e.target.reset();showDashboard();await refresh();notice('Sesión iniciada.')})};
$('providerForm').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{await api('provider-save',fields(e.target));resetConnection();await refresh();notice('Conexión agregada o actualizada. Se conservan los paneles anteriores.')})};
async function refresh(){const [list,info,connections,xtream]=await Promise.all([api('users'),api('overview'),api('connections'),api('xtream-settings')]);renderXtream(xtream);renderConnections(connections);users=list;seriesView.setUsers(users);render();$('providerStatus').textContent=info.provider?(info.provider.mode==='panel'?(info.provider.sourceCount||1)+' conexiones guardadas · '+info.provider.activeAccounts+' cuentas activas':'Cuenta conectada: '+info.provider.username)+' · '+info.connections+' / '+info.provider.maxConnections+' reproducciones / plazas totales':'Todavía no hay servidores conectados.';$('summary').textContent=users.length+' usuarios · '+users.filter(u=>u.status==='active'&&(!u.expiresAt||u.expiresAt>Date.now())).length+' activos · '+users.filter(u=>u.status==='suspended').length+' suspendidos.';await providerView.load(false);await Promise.all([securityView.refresh(),operationsView.refresh()])}
function render(){const q=$('filter').value.toLowerCase();$('rows').replaceChildren();for(const u of users.filter(u=>(u.username+' '+u.name).toLowerCase().includes(q))){const tr=document.createElement('tr');for(const text of [u.username,u.name,u.expiresAt&&u.expiresAt<=Date.now()?'Vencido':u.status==='active'?'Activo':'Suspendido',u.expiresAt?new Date(u.expiresAt).toLocaleString():'Sin vencimiento']){const td=document.createElement('td');td.textContent=text;tr.append(td)}const access=document.createElement('td');for(const [key,label]of [['movies','Películas'],['series','Series'],['tv','TV'],['adults','Adultos (+18)']]){const wrap=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.style.width='auto';check.checked=(u.permissions||{movies:true,series:true,tv:true})[key]!==false;check.setAttribute('aria-label',label+' para '+u.username);check.onchange=async()=>{check.disabled=true;try{await api('save',{...u,create:false,permissions:{...(u.permissions||{movies:true,series:true,tv:true}),[key]:check.checked}});await refresh();notice('Permisos guardados. El usuario debe iniciar sesión nuevamente.')}catch(e){check.checked=!check.checked;notice(e.message)}finally{check.disabled=false}};wrap.append(check,document.createTextNode(' '+label));access.append(wrap)}tr.append(access);const actions=document.createElement('td');for(const [label,fn,danger]of [['Editar',()=>edit(u)], [u.status==='active'?'Suspender':'Activar',()=>toggle(u)],['Borrar',()=>remove(u),true]]){const b=document.createElement('button');b.type='button';b.className=danger?'danger':'secondary';b.textContent=label;b.onclick=()=>Promise.resolve(fn()).catch(e=>notice(e.message));actions.append(b)}tr.append(actions);$('rows').append(tr)}}
function edit(u){creating=!u;const f=$('userForm');f.reset();f.elements.username.value=u?.username||'';f.elements.username.readOnly=!!u;f.elements.name.value=u?.name||'';f.elements.status.value=u?.status||'active';for(const key of ['movies','series','tv','adults'])f.elements[key].checked=(u?.permissions||{movies:true,series:true,tv:true})[key]!==false;f.elements.password.required=!u;$('passwordHint').textContent=u?'Vacío: conservar contraseña. Mínimo 12 caracteres.':'Mínimo 12 caracteres.';if(u?.expiresAt){const d=new Date(u.expiresAt);f.elements.expiresAt.value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}$('editorTitle').textContent=u?'Editar usuario':'Crear usuario';$('editor').showModal()}
$('userForm').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{const b=fields(e.target);b.permissions=Object.fromEntries(['movies','series','tv','adults'].map(key=>[key,e.target.elements[key].checked]));delete b.movies;delete b.series;delete b.tv;delete b.adults;b.expiresAt=b.expiresAt?new Date(b.expiresAt).getTime():null;b.create=creating;await api('save',b);$('editor').close();e.target.reset();await refresh();notice(creating?'Usuario creado. Ya puede entrar a SNAPMOVIENOW.':'Usuario actualizado; sus sesiones anteriores fueron revocadas.')})};
async function toggle(u){if(u.expiresAt&&u.expiresAt<=Date.now()&&u.status==='suspended'){edit(u);notice('Actualiza también el vencimiento para activar esta cuenta.');return}await api('save',{...u,status:u.status==='active'?'suspended':'active',create:false});await refresh();notice('Estado actualizado y sesiones revocadas.')}
async function remove(u){if(!confirm('¿Borrar permanentemente la cuenta '+u.username+' y revocar su acceso?'))return;await api('delete',{username:u.username});await refresh();notice('Cuenta borrada y acceso revocado.')}
function resetConnection(){const form=$('providerForm');form.reset();form.elements.source.value='';form.elements.password.required=true;form.elements.password.placeholder='';form.elements.url.value='http://ccf.center:8444/NYzkggyG/'}
function renderConnections(items){const box=$('connections');box.replaceChildren();for(const item of items){const card=document.createElement('article');card.style.cssText='border:1px solid var(--line);padding:14px;border-radius:10px;margin-bottom:12px';const title=document.createElement('strong');title.textContent=item.name;const address=document.createElement('p');address.textContent=item.url;address.style.overflowWrap='anywhere';const edit=document.createElement('button');edit.type='button';edit.className='secondary';edit.textContent='Editar';edit.onclick=()=>{const f=$('providerForm');f.elements.source.value=item.source;for(const key of ['name','url','origin','mode','username'])f.elements[key].value=item[key]||'';f.elements.password.value='';f.elements.password.required=false;f.elements.password.placeholder='Vacío: conservar contraseña';f.scrollIntoView({behavior:'smooth',block:'center'})};const remove=document.createElement('button');remove.type='button';remove.className='danger';remove.textContent='Retirar';remove.onclick=async()=>{if(!confirm('¿Retirar la conexión '+item.name+'? Podrás agregarla de nuevo. Las reproducciones que dependan de ella terminarán.'))return;try{await api('provider-remove',{source:item.source});resetConnection();await refresh();notice('Conexión retirada.')}catch(e){notice(e.message)}};card.append(title,address,edit,document.createTextNode(' '),remove);box.append(card)}}
function renderXtream(settings){$('xtreamEnabled').checked=settings.enabled;$('xtreamUrl').value=settings.url;$('xtreamPort').value=settings.port;$('xtreamStatus').textContent=settings.enabled?'Acceso Xtream habilitado. Los clientes utilizan sus propias cuentas de este panel.':'Acceso Xtream deshabilitado.'}
$('xtreamEnabled').onchange=async e=>{const check=e.target,enabled=check.checked;check.disabled=true;try{renderXtream(await api('xtream-save',{enabled}));notice(enabled?'Acceso Xtream habilitado.':'Acceso Xtream deshabilitado; sus reproducciones anteriores se revocaron.')}catch(error){check.checked=!enabled;notice(error.message)}finally{check.disabled=false}};
$('copyXtream').onclick=async()=>{try{await navigator.clipboard.writeText($('xtreamUrl').value);notice('URL copiada. Pégala completa en el campo URL de Smarters.')}catch{$('xtreamUrl').focus();$('xtreamUrl').select();notice('Mantén pulsada la URL seleccionada y elige Copiar.')}};
$('checkAPI').onclick=async e=>{e.target.disabled=true;$('apiDiagnosis').textContent='Comprobando…';try{const result=await SMNConnection.check(new URL(API).origin);$('apiDiagnosis').textContent='Servidor accesible · versión '+result.version+' · '+result.elapsedMs+' ms · acceso Xtream protegido. Comprobado: '+result.checkedAt+'. Referencia: '+(result.rayId||result.requestId||'no disponible')+'. Esta prueba no valida las señales del proveedor.'}catch(error){$('apiDiagnosis').textContent=SMNConnection.message(error,'No se pudo completar el diagnóstico.')}finally{e.target.disabled=false}};
$('checkXtream').onclick=async e=>{e.target.disabled=true;try{const result=await api('xtream-check');$('xtreamStatus').textContent=result.compatible?(result.enabled?'La interfaz Xtream responde correctamente. La reproducción necesita una cuenta activa del proveedor.':'La interfaz responde, pero el acceso Xtream está deshabilitado.'):'La interfaz Xtream no respondió como se esperaba.'}catch(error){notice(error.message)}finally{e.target.disabled=false}};
$('cancelConnection').onclick=resetConnection;$('providerForm').elements.mode.onchange=e=>{if(!$('providerForm').elements.source.value)$('providerForm').elements.url.value=e.target.value==='panel'?'http://ccf.center:8444/NYzkggyG/':'http://ccf.center:8444'};
$('newUser').onclick=()=>edit();$('cancel').onclick=()=>$('editor').close();$('filter').oninput=render;$('refresh').onclick=()=>refresh().catch(e=>notice(e.message));$('exit').onclick=async()=>{const closing=api('logout').catch(()=>{});token=null;sessionStorage.removeItem('smn_admin_token');users=[];$('rows').replaceChildren();showLogin();notice('Sesión cerrada.');await closing};
setInterval(()=>{if(token&&!document.hidden&&!$('dashboard').classList.contains('hidden'))providerView.load(false)},30000);
(async()=>{try{const s=await api('status');if(!s.configured){$('login').classList.add('hidden');$('setup').classList.remove('hidden');if(!s.setupAvailable)notice('Falta configurar ADMIN_SETUP_SECRET en Cloudflare para activar este panel.')}else if(token){showDashboard();await refresh()}}catch(e){notice(e.message)}})();
