import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
const ctx=vm.createContext({performance});vm.runInContext(readFileSync(new URL('../playback-metrics.js',import.meta.url),'utf8'),ctx);
let clock=0,tick,cancelled=0,hidden=false,reports=[];const listeners=new Map(),video={paused:true,seeking:false,addEventListener:(n,f)=>listeners.set(n,f),removeEventListener:n=>listeners.delete(n),getVideoPlaybackQuality:()=>({totalVideoFrames:100,droppedVideoFrames:2})};
const tracker=ctx.createPlaybackMetrics(video,{now:()=>clock,send:async m=>reports.push(m),schedule:fn=>{tick=fn;return 1},cancel:()=>cancelled++,hidden:()=>hidden});
clock=10000;await tracker.flush();assert.equal(reports.length,0);video.paused=false;clock=12000;listeners.get('playing')();
for(let i=0;i<5;i++){clock+=1000;tick()}listeners.get('waiting')();for(let i=0;i<2;i++){clock+=1000;tick()}listeners.get('playing')();video.paused=true;listeners.get('pause')();clock+=1000;tick();await tracker.flush();
assert.equal(reports[0].started,true,'a flush before playing cannot lose the startup sample');assert.equal(reports[0].startupMs,12000);assert.equal(reports[0].watchMs,7000);assert.equal(reports[0].stallMs,2000);assert.equal(reports[0].stalls,1);
tracker.error();await tracker.flush();assert.equal(reports[1].started,false);assert.equal(reports[1].startupMs,null);assert.equal(reports[1].errors,1);tracker.stop();tracker.stop();assert.equal(cancelled,1);assert.equal(listeners.size,0);
let legacyCalls=0;const legacy=ctx.createPlaybackMetrics(video,{now:()=>clock,send:async()=>{legacyCalls++;throw Error('operation_not_allowed')},schedule:fn=>{tick=fn;return 2},cancel:()=>{},hidden:()=>false});legacy.error();await legacy.flush();legacy.error();await legacy.flush();assert.equal(legacyCalls,1,'an older server does not receive repeated unsupported telemetry requests');legacy.stop();
let attempts=[],fails=true,resolveSend;video.paused=false;clock=0;
const retried=ctx.createPlaybackMetrics(video,{now:()=>clock,send:async m=>{attempts.push(m);if(fails)throw Error('network_failed');return{ok:true}},schedule:fn=>{tick=fn;return 3},cancel:()=>{},hidden:()=>false});
clock=1500;listeners.get('playing')();retried.addBytes(2048);await retried.flush();assert.equal(attempts.length,1);fails=false;await retried.flush();assert.equal(attempts.length,2);assert.equal(attempts[0].report_id,attempts[1].report_id,'retry preserves idempotency identity');assert.equal(attempts[1].startupMs,1500);assert.equal(attempts[1].bytes,2048);assert.equal(attempts[1].attempted,true);await retried.flush();assert.equal(attempts.length,2,'idle flush does not manufacture empty samples');await retried.stop();
let finalReports=[];video.paused=true;
const failed=ctx.createPlaybackMetrics(video,{now:()=>clock,send:async m=>finalReports.push(m),schedule:()=>4,cancel:()=>{},hidden:()=>false});await failed.stop();assert.equal(finalReports.length,1);assert.equal(finalReports[0].failedStart,true);assert.equal(finalReports[0].attempted,true);assert.equal(finalReports[0].started,false);
let heldCalls=0,release;video.paused=false;
const held=ctx.createPlaybackMetrics(video,{now:()=>clock,send:()=>{heldCalls++;return new Promise(r=>release=r)},schedule:()=>5,cancel:()=>{},hidden:()=>false});listeners.get('playing')();const firstSend=held.flush(),secondSend=held.flush();await Promise.resolve();assert.equal(heldCalls,1,'parallel flushes share the in-flight report');release({ok:true});await Promise.all([firstSend,secondSend]);await held.stop();
console.log('PASS: delayed startup, exact watch/stall counters, pause exclusion, one startup sample, cleanup and older-backend fallback.');

let syncAttempts=0;const syncFail=ctx.createPlaybackMetrics(video,{now:()=>clock,send:()=>{if(++syncAttempts===1)throw Error('offline');return{ok:true}},schedule:()=>6,cancel:()=>{},hidden:()=>false});syncFail.error();await syncFail.flush();await syncFail.flush();assert.equal(syncAttempts,2);await syncFail.stop();
