const ORIGIN="http://ccf.center:8444";
const SITE="https://snapmovienow.github.io";
const actions={vod_categories:"get_vod_categories",vod:"get_vod_streams",series_categories:"get_series_categories",series:"get_series",series_info:"get_series_info",vod_info:"get_vod_info"};
const cors={"Access-Control-Allow-Origin":SITE,"Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"content-type, range, if-range","Access-Control-Expose-Headers":"Content-Length, Content-Range, Accept-Ranges, ETag, Last-Modified","Cache-Control":"no-store"};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"content-type":"application/json"}});
const cleanExt=x=>String(x||"mp4").replace(/[^a-zA-Z0-9]/g,"")||"mp4";
async function aesKey(secret){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(secret));return crypto.subtle.importKey("raw",digest,{name:"AES-GCM"},false,["encrypt","decrypt"])}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const unb64=s=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
async function ticket(env,data){if(!env.TICKET_SECRET)throw new Error("TICKET_SECRET missing");const iv=crypto.getRandomValues(new Uint8Array(12));const ct=await crypto.subtle.encrypt({name:"AES-GCM",iv},await aesKey(env.TICKET_SECRET),new TextEncoder().encode(JSON.stringify(data)));const out=new Uint8Array(iv.length+ct.byteLength);out.set(iv);out.set(new Uint8Array(ct),iv.length);return b64(out)}
async function unticket(env,t){try{if(!env.TICKET_SECRET)return null;const raw=unb64(t);if(raw.length<29)return null;const iv=raw.slice(0,12),ct=raw.slice(12);const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv},await aesKey(env.TICKET_SECRET),ct);const d=JSON.parse(new TextDecoder().decode(plain));return d.exp>Date.now()?d:null}catch{return null}}
export default{async fetch(req,env){const u=new URL(req.url);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});
if(u.pathname==="/health")return json({ok:true,service:"snapmovienow-edge",version:"5"});
if(u.pathname==="/stream"&&req.method==="GET"){try{const d=await unticket(env,u.searchParams.get("t")||"");if(!d)return new Response("Expired",{status:410,headers:cors});const folder=d.type==="series"?"series":"movie";const target=ORIGIN+"/"+folder+"/"+encodeURIComponent(d.username)+"/"+encodeURIComponent(d.password)+"/"+encodeURIComponent(d.id)+"."+cleanExt(d.ext);const h=new Headers({"User-Agent":"SnapMovieNow/1.0"});for(const n of ["range","if-range"])if(req.headers.get(n))h.set(n,req.headers.get(n));let next=target,up;for(let redirects=0;redirects<6;redirects++){up=await fetch(next,{headers:h,redirect:"manual"});if(![301,302,303,307,308].includes(up.status))break;const location=up.headers.get("location");if(!location)return json({error:"upstream_redirect_invalid"},502);const dest=new URL(location,next);if(dest.hostname==="194.76.0.119"&&dest.port==="8080"&&dest.protocol==="http:")dest.hostname="media.snaptvnow.com";if(/^(?:\d{1,3}\.){3}\d{1,3}$/.test(dest.hostname)||dest.hostname.startsWith("[")){await up.body?.cancel();return json({error:"upstream_hostname_required",upstream:{hostname:dest.hostname,port:dest.port,protocol:dest.protocol}},502)}if(!["http:","https:"].includes(dest.protocol))return json({error:"upstream_redirect_invalid"},502);await up.body?.cancel();next=dest.href;if(redirects===5)return json({error:"upstream_redirect_limit"},502)}const out=new Headers(cors);for(const n of ["content-type","content-length","content-range","accept-ranges","etag","last-modified"]){const v=up.headers.get(n);if(v)out.set(n,v)}return new Response(up.body,{status:up.status,headers:out})}catch{return new Response("Stream unavailable",{status:502,headers:cors})}}
if(req.method!=="POST")return json({error:"method_not_allowed"},405);
try{const b=await req.json(),op=String(b.op||"");if(op!=="auth"&&op!=="stream_token"&&!Object.hasOwn(actions,op))return json({error:"operation_not_allowed"},403);if(!b.username||!b.password)return json({error:"credentials_required"},400);
if(op==="stream_token"){const t=await ticket(env,{username:String(b.username),password:String(b.password),type:String(b.type||"movie"),id:String(b.id||""),ext:cleanExt(b.ext),exp:Date.now()+12*60*60*1000});return json({url:u.origin+"/stream?t="+t})}
const x=new URL(ORIGIN+"/player_api.php");x.searchParams.set("username",String(b.username));x.searchParams.set("password",String(b.password));if(op!=="auth")x.searchParams.set("action",actions[op]);if(op==="series_info"&&b.series_id)x.searchParams.set("series_id",String(b.series_id));if(op==="vod_info"&&b.vod_id)x.searchParams.set("vod_id",String(b.vod_id));const up=await fetch(x,{headers:{"User-Agent":"SnapMovieNow/1.0"},redirect:"follow"});return new Response(await up.text(),{status:up.status,headers:{...cors,"content-type":up.headers.get("content-type")||"application/json"}})}catch{return json({error:"upstream_unavailable"},502)}}};