const ORIGIN="http://ccf.center:8444";
const SITE="https://snapmovienow.github.io";
const actions={vod_categories:"get_vod_categories",vod:"get_vod_streams",series_categories:"get_series_categories",series:"get_series",series_info:"get_series_info",vod_info:"get_vod_info"};
const cors={"Access-Control-Allow-Origin":SITE,"Access-Control-Allow-Methods":"GET, HEAD, POST, OPTIONS","Access-Control-Allow-Headers":"content-type, range, if-range","Access-Control-Expose-Headers":"Content-Length, Content-Range, Accept-Ranges, ETag, Last-Modified","Cache-Control":"no-store"};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"content-type":"application/json"}});
const cleanExt=x=>String(x||"mp4").replace(/[^a-zA-Z0-9]/g,"")||"mp4";
async function aesKey(secret){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(secret));return crypto.subtle.importKey("raw",digest,{name:"AES-GCM"},false,["encrypt","decrypt"])}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const unb64=s=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
async function ticket(env,data){if(!env.TICKET_SECRET)throw new Error("TICKET_SECRET missing");const iv=crypto.getRandomValues(new Uint8Array(12));const ct=await crypto.subtle.encrypt({name:"AES-GCM",iv},await aesKey(env.TICKET_SECRET),new TextEncoder().encode(JSON.stringify(data)));const out=new Uint8Array(iv.length+ct.byteLength);out.set(iv);out.set(new Uint8Array(ct),iv.length);return b64(out)}
async function unticket(env,t){try{if(!env.TICKET_SECRET)return null;const raw=unb64(t);if(raw.length<29)return null;const iv=raw.slice(0,12),ct=raw.slice(12);const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv},await aesKey(env.TICKET_SECRET),ct);const d=JSON.parse(new TextDecoder().decode(plain));return d.exp>Date.now()?d:null}catch{return null}}

export class PlaybackSession {
 constructor(state){this.state=state}
 async fetch(req){const path=new URL(req.url).pathname;if(path==="/create"){const {exp}=await req.json();await this.state.storage.put("exp",exp);await this.state.storage.setAlarm(exp);return new Response("ok")}
 if(path==="/logout"){await this.state.storage.deleteAll();return new Response("ok")}
 const exp=await this.state.storage.get("exp");return new Response(exp>Date.now()?"ok":"expired",{status:exp>Date.now()?200:401})}
 async alarm(){await this.state.storage.deleteAll()}
}
async function sessionCall(env,sid,path,body){if(!env.PLAYBACK_SESSIONS||!sid)return new Response("Unauthorized",{status:401});return env.PLAYBACK_SESSIONS.get(env.PLAYBACK_SESSIONS.idFromName(sid)).fetch("https://session"+path,{method:body?"POST":"GET",...(body?{body:JSON.stringify(body)}:{})})}
async function createSession(env,username,password){const sid=crypto.randomUUID(),exp=Date.now()+12*60*60*1000;const r=await sessionCall(env,sid,"/create",{exp});if(!r.ok)throw Error("session_unavailable");return {sid,username,password,exp,kind:"session"}}
async function validateAccount(username,password){const x=new URL(ORIGIN+"/player_api.php");x.searchParams.set("username",username);x.searchParams.set("password",password);const r=await fetch(x,{headers:{"User-Agent":"SnapMovieNow/1.0"}});const a=await r.json();return r.ok&&String(a?.user_info?.auth)==="1"&&(!a.user_info.status||a.user_info.status==="Active")?a:null}
const GNULA_PAGE="https://www2.gnula.one/movie/batman-vs-superman-el-origen-de-la-justicia/";
const gnulaMovie={stream_id:"gnula-batman-v-superman",source:"gnula",name:"Batman vs. Superman: El origen de la justicia",container_extension:"m3u8",plot:"Batman se enfrenta a Superman mientras una nueva amenaza pone en peligro a la humanidad."};
async function resolveGnula(){const page=await fetch(GNULA_PAGE,{headers:{"User-Agent":"Mozilla/5.0"}});if(!page.ok)throw Error("source_unavailable");const html=await page.text();const embed=html.match(/https:\/\/uqload\.(?:com|vc)\/embed-[a-z0-9]+\.html/i)?.[0];if(!embed)throw Error("source_missing");const r=await fetch(embed,{headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)throw Error("embed_unavailable");const text=await r.text();let config=text;
 const packed=text.match(/\}\('((?:\\.|[^'])*)',(\d+),(\d+),'([^']*)'\.split\('\|'\)/);
 if(packed){const radix=Number(packed[2]),words=packed[4].split("|");if(radix<2||radix>36)throw Error("unsupported_config");config=packed[1].replace(/\b[0-9a-z]+\b/g,v=>{const i=parseInt(v,radix);return Number.isFinite(i)&&words[i]?words[i]:v})}
 const source=config.match(/file\s*:\s*"(https:[^"]+\.m3u8[^"]*)"/)?.[1];if(!source||!allowedGnula(new URL(source)))throw Error("media_missing");return source}
function allowedGnula(u){return u.protocol==="https:"&&/^strm\d+\.uqload\.vc$/.test(u.hostname)&&!u.port&&!u.username&&!u.password}
function proxiedMedia(origin,t,url){return origin+"/gnula-media?t="+encodeURIComponent(t)+"&path="+encodeURIComponent(url)}
async function gnulaMedia(req,env,u){const t=u.searchParams.get("t")||"",d=await unticket(env,t);if(d?.kind!=="gnula"||!(await sessionCall(env,d.sid,"/check")).ok)return json({error:"session_expired"},401);
 const base=new URL(d.source),target=new URL(u.searchParams.get("path")||d.source);const directory=base.pathname.slice(0,base.pathname.lastIndexOf("/")+1);
 if(!allowedGnula(target)||target.hostname!==base.hostname||!target.pathname.startsWith(directory))return json({error:"media_not_allowed"},403);
 const headers=new Headers({"User-Agent":"Mozilla/5.0"});if(req.headers.has("range"))headers.set("range",req.headers.get("range"));const r=await fetch(target.href,{headers,redirect:"manual"});if(r.status>=300&&r.status<400)return json({error:"media_redirect_not_allowed"},502);
 if(!r.ok)return json({error:"media_unavailable"},r.status===404?404:502);
 const out=new Headers(cors);for(const n of ["content-type","content-length","content-range","accept-ranges"])if(r.headers.has(n))out.set(n,r.headers.get(n));
 if(target.pathname.endsWith(".m3u8")){const text=await r.text();if(!text.startsWith("#EXTM3U"))return json({error:"invalid_playlist"},502);const rewrite=x=>{const url=new URL(x,target);if(!allowedGnula(url)||url.hostname!==base.hostname||!url.pathname.startsWith(directory))throw Error("playlist_url_not_allowed");return proxiedMedia(u.origin,t,url.href)};
 const playlist=text.split(/\r?\n/).map(line=>!line.trim()?line:line.startsWith("#")?line.replace(/URI="([^"]+)"/g,(_,url)=>'URI="'+rewrite(url)+'"'):rewrite(line.trim())).join("\n");out.delete("content-length");out.set("content-type","application/vnd.apple.mpegurl");return new Response(req.method==="HEAD"?null:playlist,{headers:out})}
 return new Response(req.method==="HEAD"?null:r.body,{status:r.status,headers:out})
}

export default{async fetch(req,env){const u=new URL(req.url);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});
if(u.pathname==="/health")return json({ok:true,service:"snapmovienow-edge",version:"7"});
if(u.pathname==="/gnula-media"&&["GET","HEAD"].includes(req.method)){try{return await gnulaMedia(req,env,u)}catch{return json({error:"media_unavailable"},502)}}
if(u.pathname==="/stream"&&["GET","HEAD"].includes(req.method)){try{const d=await unticket(env,u.searchParams.get("t")||"");if(!d||!(await sessionCall(env,d.sid,"/check")).ok)return new Response("Expired",{status:410,headers:cors});const folder=d.type==="series"?"series":"movie";const target=ORIGIN+"/"+folder+"/"+encodeURIComponent(d.username)+"/"+encodeURIComponent(d.password)+"/"+encodeURIComponent(d.id)+"."+cleanExt(d.ext);const h=new Headers({"User-Agent":"SnapMovieNow/1.0"});for(const n of ["range","if-range"])if(req.headers.get(n))h.set(n,req.headers.get(n));if(req.method==="HEAD")h.set("range","bytes=0-0");let next=target,up;for(let redirects=0;redirects<6;redirects++){up=await fetch(next,{headers:h,redirect:"manual"});if(![301,302,303,307,308].includes(up.status))break;const location=up.headers.get("location");if(!location)return json({error:"upstream_redirect_invalid"},502);const dest=new URL(location,next);if(dest.hostname==="194.76.0.119"&&dest.port==="8080"&&dest.protocol==="http:")dest.hostname="media.snaptvnow.com";if(/^(?:\d{1,3}\.){3}\d{1,3}$/.test(dest.hostname)||dest.hostname.startsWith("[")){await up.body?.cancel();return json({error:"upstream_hostname_required",upstream:{hostname:dest.hostname,port:dest.port,protocol:dest.protocol}},502)}if(!["http:","https:"].includes(dest.protocol))return json({error:"upstream_redirect_invalid"},502);await up.body?.cancel();next=dest.href;if(redirects===5)return json({error:"upstream_redirect_limit"},502)}const out=new Headers(cors);for(const n of ["content-type","content-length","content-range","accept-ranges","etag","last-modified"]){const v=up.headers.get(n);if(v)out.set(n,v)}if(req.method==="HEAD"){const total=up.headers.get("content-range")?.match(/\/(\d+)$/)?.[1];if(total)out.set("content-length",total);out.delete("content-range");await up.body?.cancel();return new Response(null,{status:up.status===206?200:up.status,headers:out})}return new Response(up.body,{status:up.status,headers:out})}catch{return new Response("Stream unavailable",{status:502,headers:cors})}}
if(req.method!=="POST")return json({error:"method_not_allowed"},405);
try{const b=await req.json(),op=String(b.op||"");if(!["auth","logout","gnula_catalog","gnula_token","stream_token"].includes(op)&&!Object.hasOwn(actions,op))return json({error:"operation_not_allowed"},403);
if(op==="auth"){if(!b.username||!b.password)return json({error:"credentials_required"},400);const a=await validateAccount(String(b.username),String(b.password));if(!a)return json({error:"invalid_credentials"},401);const old=await unticket(env,String(b.access_token||""));if(old?.kind==="session"&&old.username===String(b.username))await sessionCall(env,old.sid,"/logout");const session=await createSession(env,String(b.username),String(b.password));return json({...a,access_token:await ticket(env,session)})}
let session=await unticket(env,String(b.access_token||""));if(session?.kind!=="session"||!(await sessionCall(env,session.sid,"/check")).ok)return json({error:"session_required"},401);
if(op==="logout"){await sessionCall(env,session.sid,"/logout");return json({ok:true})}
b.username=session.username;b.password=session.password;
if(op==="gnula_catalog")return json([gnulaMovie]);
if(op==="gnula_token"){if(b.id!==gnulaMovie.stream_id)return json({error:"title_not_allowed"},404);const source=await resolveGnula();const data={kind:"gnula",source,sid:session.sid,exp:Math.min(session.exp,Date.now()+3*60*60*1000)};const t=await ticket(env,data);return json({url:proxiedMedia(u.origin,t,source)})}
if(op==="stream_token"){const t=await ticket(env,{sid:session.sid,username:session.username,password:session.password,type:String(b.type||"movie"),id:String(b.id||""),ext:cleanExt(b.ext),exp:session.exp});return json({url:u.origin+"/stream?t="+t})}
const x=new URL(ORIGIN+"/player_api.php");x.searchParams.set("username",String(b.username));x.searchParams.set("password",String(b.password));if(op!=="auth")x.searchParams.set("action",actions[op]);if(op==="series_info"&&b.series_id)x.searchParams.set("series_id",String(b.series_id));if(op==="vod_info"&&b.vod_id)x.searchParams.set("vod_id",String(b.vod_id));const up=await fetch(x,{headers:{"User-Agent":"SnapMovieNow/1.0"},redirect:"follow"});return new Response(await up.text(),{status:up.status,headers:{...cors,"content-type":up.headers.get("content-type")||"application/json"}})}catch{return json({error:"upstream_unavailable"},502)}}};
