const ORIGIN="http://ccf.center:8444";
const SITE="https://snapmovienow.github.io";
const actions={vod_categories:"get_vod_categories",vod:"get_vod_streams",series_categories:"get_series_categories",series:"get_series",series_info:"get_series_info",vod_info:"get_vod_info"};
const cors={"Access-Control-Allow-Origin":SITE,"Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"content-type, range, if-range","Access-Control-Expose-Headers":"Content-Length, Content-Range, Accept-Ranges, ETag, Last-Modified","Cache-Control":"no-store"};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"content-type":"application/json"}});
const cleanExt=x=>String(x||"mp4").replace(/[^a-zA-Z0-9]/g,"")||"mp4";
async function key(secret){return crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign","verify"])}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const unb64=s=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
async function ticket(env,data){const p=b64(new TextEncoder().encode(JSON.stringify(data)));const sig=b64(await crypto.subtle.sign("HMAC",await key(env.TICKET_SECRET),new TextEncoder().encode(p)));return p+"."+sig}
async function unticket(env,t){const [p,s]=t.split(".");if(!p||!s)return null;const ok=await crypto.subtle.verify("HMAC",await key(env.TICKET_SECRET),unb64(s),new TextEncoder().encode(p));if(!ok)return null;const d=JSON.parse(new TextDecoder().decode(unb64(p)));return d.exp>Date.now()?d:null}
export default{async fetch(req,env){const u=new URL(req.url);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});
if(u.pathname==="/health")return json({ok:true,service:"snapmovienow-edge",version:"1"});
if(u.pathname==="/stream"&&req.method==="GET"){try{const d=await unticket(env,u.searchParams.get("t")||"");if(!d)return new Response("Expired",{status:410,headers:cors});const folder=d.type==="series"?"series":"movie";const target=ORIGIN+"/"+folder+"/"+encodeURIComponent(d.username)+"/"+encodeURIComponent(d.password)+"/"+encodeURIComponent(d.id)+"."+cleanExt(d.ext);const h=new Headers();for(const n of ["range","if-range"])if(req.headers.get(n))h.set(n,req.headers.get(n));const up=await fetch(target,{headers:h,redirect:"follow"});const out=new Headers(cors);for(const n of ["content-type","content-length","content-range","accept-ranges","etag","last-modified"]){const v=up.headers.get(n);if(v)out.set(n,v)}return new Response(up.body,{status:up.status,headers:out})}catch{return new Response("Stream unavailable",{status:502,headers:cors})}}
if(req.method!=="POST")return json({error:"method_not_allowed"},405);
try{const b=await req.json(),op=String(b.op||"");if(op!=="auth"&&op!=="stream_token"&&!Object.hasOwn(actions,op))return json({error:"operation_not_allowed"},403);if(!b.username||!b.password)return json({error:"credentials_required"},400);
if(op==="stream_token"){const t=await ticket(env,{username:String(b.username),password:String(b.password),type:String(b.type||"movie"),id:String(b.id||""),ext:cleanExt(b.ext),exp:Date.now()+12*60*60*1000});return json({url:u.origin+"/stream?t="+t})}
const x=new URL(ORIGIN+"/player_api.php");x.searchParams.set("username",String(b.username));x.searchParams.set("password",String(b.password));if(op!=="auth")x.searchParams.set("action",actions[op]);if(op==="series_info"&&b.series_id)x.searchParams.set("series_id",String(b.series_id));if(op==="vod_info"&&b.vod_id)x.searchParams.set("vod_id",String(b.vod_id));const up=await fetch(x,{redirect:"follow"});return new Response(await up.text(),{status:up.status,headers:{...cors,"content-type":up.headers.get("content-type")||"application/json"}})}catch{return json({error:"upstream_unavailable"},502)}}};