import assert from 'node:assert/strict';import worker,{PlaybackSession} from '../src/index.js';import {validateServerUrl} from '../src/reseller.mjs';
class Store{constructor(){this.data=new Map();this.queue=Promise.resolve()}async get(k){return structuredClone(this.data.get(k))}async put(k,v){this.data.set(k,structuredClone(v))}async delete(k){this.data.delete(k)}async deleteAll(){this.data.clear()}async setAlarm(){}async list({prefix}){return new Map([...this.data].filter(([k])=>k.startsWith(prefix)))}transaction(fn){const r=this.queue.then(()=>fn(this));this.queue=r.catch(()=>{});return r}}
const objects=new Map(),env={TICKET_SECRET:'mock-secret-for-tests',ADMIN_SETUP_SECRET:'test-setup-secret-12345678901234567890'};env.PLAYBACK_SESSIONS={idFromName:x=>x,get(id){if(!objects.has(id))objects.set(id,new PlaybackSession({storage:new Store()},env));return {fetch:(url,options)=>objects.get(id).fetch(new Request(url,options))}}};
let mediaOrigins=[];globalThis.fetch=async(url,opts={})=>{const u=new URL(url);assert.ok(['http://alpha.example.com:8444','https://beta.example.com','https://edited.example.com'].includes(u.origin));if(u.pathname==='/player_api.php'){const action=u.searchParams.get('action');if(!action)return Response.json({user_info:{auth:1,status:'Active',max_connections:3,active_cons:0}});if(action==='get_live_categories')return Response.json([{category_id:'7',category_name:'Noticias'}]);if(action==='get_series_info')return Response.json({episodes:{1:[{id:44,title:'Episode'}]}});return Response.json([{stream_id:123,series_id:22,category_id:'7',name:u.hostname,container_extension:'mp4'}])}mediaOrigins.push(u.origin);if(u.pathname.endsWith('.m3u8'))return new Response('#EXTM3U\n#EXT-X-KEY:METHOD=AES-128,URI="key.bin"\n#EXTINF:4,\nsegment.ts\n',{headers:{'content-type':'application/vnd.apple.mpegurl'}});return new Response('sample-media',{headers:{'content-type':'video/mp2t'}})};
const origin='https://edge.example.com',req=async(b,path='')=>{const r=await worker.fetch(new Request(origin+path,{method:'POST',body:JSON.stringify(b)}),env);return {status:r.status,data:await r.json()}};
assert.equal((await req({action:'connections'},'/admin')).status,401);
await req({action:'setup',setupSecret:env.ADMIN_SETUP_SECRET,username:'admin',password:'admin-password-test'},'/admin');const login=await req({action:'login',username:'admin',password:'admin-password-test'},'/admin');const admin=(action,b={})=>req({action,access_token:login.data.access_token,...b},'/admin');
for(const [name,url]of [['Alpha','http://alpha.example.com:8444'],['Beta','https://beta.example.com']])assert.equal((await admin('provider-save',{mode:'single',name,url,username:'source-test',password:'source-password-test'})).status,200);
const connections=await admin('connections');assert.equal(connections.data.length,2);assert.ok(!JSON.stringify(connections).includes('password'));
assert.equal((await admin('save',{create:true,username:'customer',password:'customer-password-test',status:'active',permissions:{movies:true,series:true,tv:true}})).status,200);
let token=(await req({op:'auth',username:'customer',password:'customer-password-test'})).data.access_token;
const catalog=await req({op:'live',access_token:token});assert.equal(catalog.data.length,2);assert.notEqual(catalog.data[0]._server,catalog.data[1]._server);
const play=await req({op:'stream_token',access_token:token,type:'live',server:catalog.data[1]._server,id:123,ext:'m3u8'});assert.equal(play.status,200);assert.ok(!play.data.url.includes('source-password-test'));
const originRequests=mediaOrigins.length;const playlist=await worker.fetch(new Request(play.data.url),env);assert.equal(playlist.status,200);const text=await playlist.text();assert.equal(mediaOrigins.length,originRequests,"validated startup playlist is reused without another origin connection");assert.ok(!text.includes('beta.example.com'));assert.ok(!text.includes('source-password-test'));const segment=text.split('\n').find(l=>l.startsWith(origin));assert.equal((await worker.fetch(new Request(segment),env)).status,200);const key=text.match(/URI="([^"]+)"/)[1];assert.equal((await worker.fetch(new Request(key),env)).status,200);assert.ok(mediaOrigins.every(x=>x==='https://beta.example.com'));
const normalFetch=globalThis.fetch;let leaked=false;globalThis.fetch=async(url,opts)=>{const u=new URL(url);if(u.hostname==='203.0.113.99'){leaked=true;throw Error('unexpected destination')}if(u.pathname.endsWith('.m3u8'))return new Response(null,{status:302,headers:{location:'http://203.0.113.99/live/test.m3u8'}});return normalFetch(url,opts)};
const blocked=await req({op:'stream_token',access_token:token,type:'live',server:catalog.data[1]._server,id:123,ext:'m3u8'});
assert.equal(blocked.status,502);assert.equal(blocked.data.error,'media_origin_unapproved');assert.equal(leaked,false);assert.equal((await admin('overview')).data.connections,0);globalThis.fetch=normalFetch;
await req({op:'logout',access_token:token});assert.equal((await worker.fetch(new Request(segment),env)).status,410);
await admin('save',{username:'customer',status:'active',permissions:{movies:true,series:true,tv:false}});token=(await req({op:'auth',username:'customer',password:'customer-password-test'})).data.access_token;
assert.equal((await req({op:'live',access_token:token})).status,403);assert.equal((await req({op:'stream_token',type:'live',id:123,access_token:token})).status,403);assert.equal((await req({op:'vod',access_token:token})).status,200);assert.equal((await req({op:'series',access_token:token})).status,200);
const edit=await admin('provider-save',{source:connections.data[1].source,mode:'single',name:'Edited',url:'https://edited.example.com',username:'source-test',password:''});assert.equal(edit.status,200);assert.equal((await admin('connections')).data.length,2);assert.equal((await req({op:'vod',access_token:token})).data[1].name,'edited.example.com');
await admin('provider-remove',{source:connections.data[0].source});assert.equal((await admin('connections')).data.length,1);assert.equal((await admin('overview')).data.provider.maxConnections,3);
assert.equal((await admin('provider-save',{mode:'single',url:'http://127.0.0.1',username:'source',password:'test-password'})).status,502);assert.equal((await admin('connections')).data.length,1);
await admin('save',{username:'customer',status:'active',permissions:{movies:false,series:true,tv:false}});assert.equal((await req({op:'vod',access_token:token})).status,401);token=(await req({op:'auth',username:'customer',password:'customer-password-test'})).data.access_token;assert.equal((await req({op:'vod',access_token:token})).status,403);assert.equal((await req({op:'gnula_catalog',access_token:token})).data.filter(x=>x.type!=='series').length,0);
for(const url of ['http://localhost','http://10.0.0.1','http://169.254.169.254','file:///tmp/test','https://user:pass@example.com','http://example.com/?secret=x'])assert.throws(()=>validateServerUrl(url));
console.log('PASS: multi-server catalogs and routed live HLS, encrypted segments/keys, logout revocation, server-side user permissions, edit with retained password, removable connections, invalid URL rejected without replacing configuration.');

